### ISSUE TITLE
forensic1394_read_device_v: General I/O error

### ISSUE THREAD

**Issue by Nicknam3** [carmaa/inception#103]
Hi,

I currently have an error by running the tool (inception on archlinux and locked computer on Windows 7 Enterprise) :

[*] FireWire devices on the bus (names may appear blank):

[1] Vendor (ID): MICROSOFT CORP. (0x50f2) | Product (ID):  (0x0)

[*] Only one device present, device auto-selected as target
[*] Selected device: MICROSOFT CORP.
[/] Initializing bus and enabling SBP-2, please wait or press Ctrl+C
[*] Available targets (known signatures):

[1] Windows 8 MsvpPasswordValidate unlock/privilege escalation
[2] Windows 7 MsvpPasswordValidate unlock/privilege escalation
[3] Windows Vista MsvpPasswordValidate unlock/privilege escalation
[4] Windows XP MsvpPasswordValidate unlock/privilege escalation
[5] Mac OS X DirectoryService/OpenDirectory unlock/privilege escalation
[6] Ubuntu libpam unlock/privilege escalation
[7] Linux Mint libpam unlock/privilege escalation

[?] Please select target (or enter 'q' to quit): 2
[*] Selected target: Windows 7 MsvpPasswordValidate unlock/privilege escalation
[>                                                                                                                                                                                  ]    0 MiB (  0%)
[!] Warning: Something went dreadfully wrong, full stack trace below: forensic1394_read_device_v: General I/O error

Traceback (most recent call last):
  File "incept", line 167, in main
    module.run(opts, memspace)
  File "/home/nickname/inception/inception/inception/modules/unlock.py", line 599, in run
    address, signature, offset = memspace.find(target, verbose=opts.verbose)
  File "/home/nickname/inception/inception/inception/memory.py", line 325, in find
    for caddr, cand in self.interface.readv(r):
  File "/usr/lib/python3.4/site-packages/forensic1394/device.py", line 174, in readv
    self._readreq(req, buf)
  File "/usr/lib/python3.4/site-packages/forensic1394/device.py", line 134, in _readreq
    forensic1394_read_device_v(self, creq, len(creq))
  File "/usr/lib/python3.4/site-packages/forensic1394/errors.py", line 61, in process_result
    raise IOError(err)
OSError: forensic1394_read_device_v: General I/O error

I used the latest version (the one published two days ago).

**Comment by dragosb91** [comment]
Hello,
This issue still persists apparently. On my setup I get the I/O timeout error everytime the module reaches 86%. I tried the unlock and dump module. What could be the reason for this? (tried it on Win 7 and Win 8.1):

sudo incept dump

| _| _| _||| _|||| ||| _||| _| _|| | _|
_| _|| | _| _| _| _| _| _| _| _| _|| |
_| _| _| _| _| _||| _||| _| _| _| _| _| _| _|
_| _| _|| | _| _| _| _| _| _| _| _||
| _| _| _||| _|||| | _| _| _|| _| _|

v.0.4.0 (C) Carsten Maartmann-Moe 2015
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

| _| _| _||| _|||| ||| _||| _| _|| | _|
_| _|| | _| _| _| _| _| _| _| _| _|| |
_| _| _| _| _| _||| _||| _| _| _| _| _| _| _|
_| _| _|| | _| _| _| _| _| _| _| _||
| _| _| _||| _|||| | _| _| _|| _| _|

v.0.4.0 (C) Carsten Maartmann-Moe 2015
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

[*] FireWire devices on the bus (names may appear blank):

[1] Vendor (ID): MICROSOFT CORP. (0x50f2) | Product (ID): (0x0)

[] Only one device present, device auto-selected as target
[] Selected device: MICROSOFT CORP.
[] Initializing bus and enabling SBP-2, please wait or press Ctrl+C
[*] Dumping from 0x0 to 0x100000000, a total of 4 GiB:
[-] Error: forensic1394_read_device_v: I/O timeout MiB ( 86%) {0350705703602c58}

Thanks

**Comment by carmaa** [comment]
See my other comment on issue #106.
