### ISSUE TITLE
incept v.0.4.0 - 'Device' object has no attribute 'businfo'

### ISSUE THREAD

**Issue by SirCosty** [carmaa/inception#107]
root@kali:~# sudo incept businfo

 _|  _|      _|    _|_|_|  _|_|_|_|  _|_|_|    _|_|_|  _|    _|_|    _|      _|
 _|  _|_|    _|  _|        _|        _|    _|    _|    _|  _|    _|  _|_|    _|
 _|  _|  _|  _|  _|        _|_|_|    _|_|_|      _|    _|  _|    _|  _|  _|  _|
 _|  _|    _|_|  _|        _|        _|          _|    _|  _|    _|  _|    _|_|
 _|  _|      _|    _|_|_|  _|_|_|_|  _|          _|    _|    _|_|    _|      _|

v.0.4.0 (C) Carsten Maartmann-Moe 2014
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

[*] FireWire devices on the bus (names may appear blank):

[1] Vendor (ID): MICROSOFT CORP. (0x50f2) | Product (ID):  (0x0)

[_] Only one device present, device auto-selected as target
[_] Selected device: MICROSOFT CORP.
[/] Initializing bus and enabling SBP-2, please wait or press Ctrl+C
[!] Warning: Something went dreadfully wrong, full stack trace below: 'Device' object has no attribute 'businfo'

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/inception-0.4.0-py3.2.egg/EGG-INFO/scripts/incept", line 168, in main
    module.run(opts, memspace)
  File "/usr/local/lib/python3.2/dist-packages/inception-0.4.0-py3.2.egg/inception/modules/businfo.py", line 36, in run
    memory.interface.businfo()
AttributeError: 'Device' object has no attribute 'businfo'

**Comment by cyphunk** [comment]
can confirm same happens on apple hardware. (Vendor ID 0xa27, Product ID 0xa)
